name: rehab4wrestling
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  better_player: any
  glass_kit: ^2.0.1
  flutter_easyloading: ^3.0.5
  human_body_selector: ^0.0.1
  form_validator: ^1.0.2
  flutter_expanded_tile: ^0.3.6
  form_field_validator: ^1.1.0
  flutter_animated_button: ^2.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^0.23.0+1
  firebase_core: ^1.22.0
  firebase_auth: ^3.4.2
dev_dependencies: 
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Sk-Modernist
      fonts:
        - asset: fonts/Sk-Modernist-Regular.otf
        - weight: 100
        - asset: fonts/Sk-Modernist-Regular.otf
        - weight: 200
        - asset: fonts/Sk-Modernist-Regular.otf
        - weight: 300
        - asset: fonts/Sk-Modernist-Regular.otf
        - weight: 400
        - asset: fonts/Sk-Modernist-Regular.otf
        - weight: 500
        - asset: fonts/Sk-Modernist-Bold.otf
        - weight: 600
        - asset: fonts/Sk-Modernist-Bold.otf
        - weight: 700
        - asset: fonts/Sk-Modernist-Bold.otf
        - weight: 800
        - asset: fonts/Sk-Modernist-Bold.otf
        - weight: 900



